export const actionTypes = {

  // USER //
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  ACK_ERROR_LOG: 'ACK_ERROR_LOG',

  // TASK //
  ADD_TASK: 'ADD_TASK',
  SET_TASK_STATUS: 'SET_TASK_STATUS',
  SET_TASK: 'SET_TASK',
  GET_TASK: 'GET_TASK',
  DEL_TASK: 'DEL_TASK',
  
};
